spring:
  application:
    name: contas
  datasource:
    url: jdbc:postgresql://localhost:5432/contas-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: 'true'
      boot:
        allow_jdbc_metadata_access: 'false'
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      usuarios: usuarios-validation
      contas: contas-validation
      orchestrator: orchestrator
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest