server:
  port: 8080

spring:
  application:
    name: orquestrador
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      start: start
      usuarios: usuarios-validation
      contas: contas-validation
      orchestrator: orchestrator
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest